[package]
name = "yoga"
version = "0.1.0"
authors = ["David Obrite <davidobrite@gmail.com>"]
build = "build.rs"

[lib]
name = "yoga"

[[bin]]
name = "yoga"
doc = false

[dependencies]
libc = "0.2.0"

[build-dependencies]
gcc = "0.3"
